In [3]:
import numpy as np

### 1. Создайте массив arr_1 размером 3x4, все элементы которого равны 3.

In [5]:
arr_1 = np.full((3, 4), 3)
arr_1

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

### 2. Создайте массив arr_2, заполненный случайными целыми числами от 0 до 9, размером 2х4.

In [6]:
arr_2 = np.random.randint(0, 9, (2, 4))
arr_2

array([[6, 5, 3, 4],
       [0, 2, 0, 4]], dtype=int32)

### 3. Выведите на экран количество элементов в созданных массивах arr_1 и arr_2.

In [12]:
print(f"arr_1 = {arr_1.size}\narr_2 = {arr_2.size}")

arr_1 = 12
arr_2 = 8


### 4. Соедините массивы arr_1 и arr_2 по нулевой оси.

In [13]:
np.concatenate([arr_1, arr_2])

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [6, 5, 3, 4],
       [0, 2, 0, 4]])

### 5. Создайте массив arr_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции np.array()

In [14]:
arr_3 = np.array((1, 8, 6, 5, 8, 3))
arr_3

array([1, 8, 6, 5, 8, 3])

### 6. Умножьте каждый элемент массива arr_3 на число 3 и прибавьте к каждому элементу 1. Результат запишите в новый массив arr_4.

In [15]:
arr_4 = (arr_3 * 3) + 1
arr_4

array([ 4, 25, 19, 16, 25, 10])

### 7. Преобразуйте масиив arr_3 к двумерному массиву 2х3. Результат запишите в массив arr_5.

In [16]:
arr_5 = arr_3.reshape(2, 3)
arr_5

array([[1, 8, 6],
       [5, 8, 3]])

### 8. Определите минимальные элементы массива arr_5 вдоль первой оси

In [17]:
np.min(arr_5, axis=1)

array([1, 3])

### 9. Вычислите среднее арифметическое всех элементов массива arr_5.

In [18]:
np.average(arr_5)

np.float64(5.166666666666667)

### 10. Создайте массив arr_6, состоящий из квадратов чисел от 0 до 10.

In [21]:
arr_6 = np.square(np.arange(0, 11))
arr_6

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### 11. Выведите каждый второй элемент массива arr_6.

In [22]:
arr_6[::2]

array([  0,   4,  16,  36,  64, 100])

### 12. Выведите элементы массива arr_6 в обратном порядке.

In [23]:
arr_6[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0])

### 13. Каждому второму элементу массива arr_6 присвойте значение 2.

In [26]:
arr_6[1::2] = 2
arr_6

array([  0,   2,   4,   2,  16,   2,  36,   2,  64,   2, 100])

### 14. Проверьте, есть ли в массиве arr_6 значение 49

In [27]:
np.any(arr_6 == 49)

np.False_

### 15. Создайте двумерный массив А, состоящий из положительных и отрицательных чисел. Из массива A выберите все отрицательные элементы и запишите их в одномерный массив B

In [33]:
A = np.random.randint(-10, 10, size=(5, 5))
print("A: ", A)
B = A[A < 0]
print("B: ", B)

A:  [[  1  -6  -9  -1  -7]
 [ -9   4   7   8 -10]
 [ -9   8   5  -7  -8]
 [  9   6   8  -6   3]
 [  0   9  -8  -6  -6]]
B:  [ -6  -9  -1  -7  -9 -10  -9  -7  -8  -6  -8  -6  -6]
